baseURL = "https://blog.joway.io/"
languageCode = "en-us"
title = "Joway's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"
enableRobotsTXT = true
canonifyURLs = false

# [related]
# includeNewer = true
# threshold = 80
# toLower = false
# [[related.indices]]
# name = "date"
# weight = 100
# [[related.indices]]
# name = "keywords"
# weight = 100

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[author]
  name = "Joway"
  homepage = "https://joway.io/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "简体中文"
    weight = 2

[permalinks]
    post = "/blog/:title/"

[params]
disqus = "joway" # disqus account name
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-53624533-8"></script><script src="https://cdn.jsdelivr.net/gh/joway/homepage/analytics.js"></script>'
extraBody = '<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>'
postAds = '<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-6400651395935595" data-ad-slot="5705651853" data-ad-format="auto" data-full-width-responsive="true"></ins>'
lazyImage = true
headTitle = "Joway Wang"
description = "一个试图有建设性的人。"
favicon = "/logo.png"
mainSections = ["posts"]
staticPrefix = "https://cdn.jsdelivr.net/gh/joway/blog"


[[params.socials]]
name = "Subscribe"
link = "https://mailchi.mp/a1a0d59e7a19/joway"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "Travel"
link = "/travel"

[[params.socials]]
name = "About"
link = "https://joway.io"
